#!/bin/bash

mkdir -p ./var/backup/test-feature
rm -rf ./var/backup/test-feature/*
cp -R ./tests/FeatureTests/backup/* ./var/backup/test-feature/
php bin/console database:drop -f
php bin/console backup:load test-feature
