expose_php = Off
memory_limit = -1
error_log = /dev/stderr

; upload limited to 101 MiB
upload_max_filesize = 105906176
post_max_size = 105906176
max_file_uploads = 1

; a single request may take at most 15 minutes, see also `read_body` in the Caddyfile; on Linux this only counts time
; in which PHP itself is working, not time spent waiting for the client or S3
max_execution_time = 900

xdebug.mode=profile
xdebug.start_with_request=trigger
xdebug.output_dir="/var/www/html/xdebug-trace"
