services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\SearchStep\EventListener\ElementHydrationSearchStepEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\SearchStep\Event\SearchStepEvent'
        method: 'onSearchStepEvent'
        priority: 0

  App\EventSystem\SearchStep\EventListener\ElasticsearchQueryDslMixinSearchStepEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\SearchStep\Event\SearchStepEvent'
        method: 'onSearchStepEvent'
        priority: 0

  App\EventSystem\SearchStep\EventListener\CypherPathSearchStepEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\SearchStep\Event\SearchStepEvent'
        method: 'onSearchStepEvent'
        priority: 0
