services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\Response\EventListener\EtagResponseEventListener:
    tags:
      - name: kernel.event_listener
        event: 'kernel.response'
        method: 'onKernelResponse'

  App\EventSystem\Response\EventListener\TusIoResponseEventListener:
    tags:
      - name: kernel.event_listener
        event: 'kernel.response'
        method: 'onKernelResponse'
