name: "Check upstream dependency - Nginx Unit"
on:
  schedule:
    - cron: "10 2 * * *"
permissions:
  contents: write
jobs:
  check-upstream-dependency-nginx-unit:
    name: 'Check upstream dependency NGINX Unit'
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load latest Docker Hub tags for Nginx Unit PHP
        run: |
          url="https://hub.docker.com/v2/namespaces/library/repositories/unit/tags?page_size=25&name=php"
          latestTags=$(wget -O - -o /dev/null $url)
          latestTag=$(echo $latestTags | jq -r '.results[] | select(.name | contains("-php")) | .name' | head -n1)
          echo "Latest tag: $latestTag"
          echo "TAG=$latestTag" >> $GITHUB_ENV

      - name: Create new GitHub issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAG: ${{ env.TAG }}
        with:
          filename: .github/ISSUE_TEMPLATE_CHECK_UPSTREAM_DEPENDENCY_NGINX_UNIT.md
          update_existing: false
          search_existing: all
